macro(CreateSymlink src dest)
    if(WIN32)
        get_filename_component(src_real ${src} REALPATH)
        get_filename_component(dest_real ${dest} REALPATH)
        string(REPLACE "/" "\\" src_rpl ${src_real})
        string(REPLACE "/" "\\" dest_rpl ${dest_real})
        execute_process(COMMAND cmd /C mklink /J "${src_rpl}" "${dest_rpl}")
    else()
        execute_process(COMMAND "ln -s ${PROJECT_SOURCE_DIR}/resources ${PROJECT_SOURCE_DIR}/bin/resources")
    endif()
endmacro()